apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cloud.tencent.com/cross-region-id: ap-shanghai
    service.cloud.tencent.com/cross-type: PVGW
    service.cloud.tencent.com/snat-pro-info: '{"snatIps":[{"subnetId":"subnet-lvb17sib"}]}'
    service.kubernetes.io/loadbalance-id: lb-nsl4falh
    service.kubernetes.io/tke-existed-lbid: lb-nsl4falh
  name: sh-cross-bj-service
  namespace: prod
spec:
  type: LoadBalancer
  ports:
  - name: 14268-14268-tcp
    port: 14268
    protocol: TCP
    targetPort: 14268
  selector:
    k8s-app: tapm-collector
    qcloud-app: tapm-collector
status:
  loadBalancer:
    ingress:
